### ISSUE TITLE
Change the integration build tag to local_integration

### ISSUE THREAD

**Issue by dimiter-todorov-georgiev** [eclipse-kanto/suite-connector#55]
These files use the `integration` build tag:
- docker/.env
- cmd/connector/it_main_test.go
- config/it_connections_test.go
- routing/it_service_test.go
- connector/pubsub_test.go
- connector/pubsub_bench_test.go
- connector/it_connection_test.go

which is used to run local integration tests inside docker.

I suggest changing this tag to `local_integration`, so that the `integration` build tag can be used by the new integration tests which use a backend.

We can also remove the old-style `+build` tagging, because go 1.17.2 supports the new-style tagging via `go:build`.

**Comment by e-grigorov** [comment]
Some more thoughts on this topic:
- in Go, there are bunch of examples where the tags are single compound word like: [gccgo, amd64p32](https://github.com/golang/sys/blob/master/cpu/cpu_gccgo_x86.go), [go1.12](https://pkg.go.dev/cmd/go#hdr-Build_constraints) but they have something in common. All of them are using short names i.e. if it's adapted here, the new tag should be: `li`. This is not accepted because we should like to have the long name `integration` for all tests from integration folder.
- As the first option is not acceptable, we have to go to another one. Long names and how to combine name. It's not an option to combine two long names like: localintegration just because it's not readable.
- As an acceptable approach is to combine two long names with a separator. There are bunch of such examples like [go-sqlite3 features](https://github.com/mattn/go-sqlite3#feature--extension-list). So, the preferred way should be: local_integration.
